global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "service-health-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["service-health-api:8000"]

  - job_name: "jenkins"
    metrics_path: /prometheus
    static_configs:
      - targets: ["jenkins:8080"]
