version: "3.9"

services:
  jenkins:
    build: ../docker/jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  service-health-api:
    build:
      context: ..
      dockerfile: docker/app/Dockerfile
    ports:
      - "8000:8000"

volumes:
  jenkins_home:
